update assign_weight to assign all layers
PaddlePaddle/PaDiff pull request #88
Opened 2023-06-29 09:19 UTC by Xing-lil

### PR types

Others
### PR changes

Others
### Description

Pcard-70448
Update assign_weight to assign all layers, not just those in the white/black list.

2023-06-29 11:20 UTC, feifei-111 commented on padiff/abstracts/marker.py
> +def traversal_all_layers(model, marker):
这个是不是可以换个名字，和权重初始化相关，因为已经有一个traversal_all了，感觉有点分不清

2023-06-29 11:20 UTC, feifei-111 commented on padiff/abstracts/marker.py
> +def traversal_all_layers(model, marker):
另外，是不是要给模型提供一个额外的接口呢？现在这个黑名单的确是分开了，但是好像没有设置的入口呀（权重初始化有时也需要用到黑名单来着）

2023-06-29 11:20 UTC, feifei-111 commented on padiff/abstracts/marker.py
> +def traversal_all_layers(model, marker):
还有哈，关于黑名单的机制，究竟是哪一种skip类型（self，sublayers，all？）应该也要考虑的

2023-07-04 06:49 UTC, FeixLiu requested changes

2023-07-04 06:49 UTC, FeixLiu commented on tests/test_accmulation_grad.py
> +class TestCaseName(unittest.TestCase):
改下ut的名，`TestGradAccumulation`之类的。

2023-07-04 23:05 UTC, FeixLiu approved these changes
LGTM for the ut

2023-07-05 03:03 UTC, feifei-111 approved these changes
LGTM

2023-07-05 03:06 UTC, merged